
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/uart 

module uart(clk, rst_n, tx_data, tx_valid, tx_ready, tx, rx_data,
     rx_valid, rx_ready, rx);
  input clk, rst_n, tx_valid, rx_ready, rx;
  input [7:0] tx_data;
  output tx_ready, tx, rx_valid;
  output [7:0] rx_data;
  wire clk, rst_n, tx_valid, rx_ready, rx;
  wire [7:0] tx_data;
  wire tx_ready, tx, rx_valid;
  wire [7:0] rx_data;
  wire [3:0] tx_bit_cnt;
  wire [3:0] rx_bit_index;
  wire [9:0] tx_shift;
  wire [7:0] rx_shift_reg;
  wire [8:0] sample_cnt;
  wire [8:0] baud_cnt;
  wire [1:0] rx_state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       baud_tick, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166;
  OAI221XL g6201(.A0 (n_165), .A1 (n_124), .B0 (n_163), .B1 (n_129),
       .C0 (n_125), .Y (n_166));
  JKFFX1 \tx_bit_cnt_reg[2] (.CK (clk), .J (n_123), .K (n_165), .Q
       (tx_bit_cnt[2]), .QN (UNCONNECTED));
  DFFHQX1 \tx_bit_cnt_reg[1] (.CK (clk), .D (n_164), .Q
       (tx_bit_cnt[1]));
  DFFHQX1 \rx_bit_index_reg[3] (.CK (clk), .D (n_162), .Q
       (rx_bit_index[3]));
  OAI2BB2XL g6211(.A0N (tx_bit_cnt[1]), .A1N (n_161), .B0 (n_130), .B1
       (n_163), .Y (n_164));
  OAI2BB1XL g6236(.A0N (rx_bit_index[3]), .A1N (n_150), .B0 (n_158), .Y
       (n_162));
  DFFHQX1 \tx_shift_reg[1] (.CK (clk), .D (n_154), .Q (tx_shift[1]));
  DFFHQX1 \tx_shift_reg[2] (.CK (clk), .D (n_155), .Q (tx_shift[2]));
  DFFHQX1 \tx_shift_reg[4] (.CK (clk), .D (n_152), .Q (tx_shift[4]));
  DFFHQX1 \tx_shift_reg[5] (.CK (clk), .D (n_160), .Q (tx_shift[5]));
  DFFHQX1 \tx_shift_reg[6] (.CK (clk), .D (n_157), .Q (tx_shift[6]));
  DFFHQX1 \tx_shift_reg[7] (.CK (clk), .D (n_156), .Q (tx_shift[7]));
  DFFHQX1 \tx_shift_reg[3] (.CK (clk), .D (n_153), .Q (tx_shift[3]));
  AOI2BB1XL g6218(.A0N (n_163), .A1N (tx_bit_cnt[1]), .B0 (n_161), .Y
       (n_165));
  DFFHQX1 \tx_shift_reg[0] (.CK (clk), .D (n_149), .Q (tx));
  DFFX1 tx_busy_reg(.CK (clk), .D (n_148), .Q (UNCONNECTED0), .QN
       (tx_ready));
  NAND2XL g6208(.A (rst_n), .B (n_140), .Y (n_160));
  OAI211XL g6248(.A0 (n_59), .A1 (n_108), .B0 (n_158), .C0 (n_118), .Y
       (n_159));
  NAND2XL g6209(.A (rst_n), .B (n_139), .Y (n_157));
  NAND2XL g6210(.A (rst_n), .B (n_138), .Y (n_156));
  NAND2XL g6205(.A (rst_n), .B (n_135), .Y (n_155));
  NAND2XL g6204(.A (rst_n), .B (n_136), .Y (n_154));
  NAND2XL g6206(.A (rst_n), .B (n_147), .Y (n_153));
  NAND2XL g6207(.A (rst_n), .B (n_145), .Y (n_152));
  SDFFTRX1 \tx_bit_cnt_reg[0] (.CK (clk), .D (n_128), .RN (baud_tick),
       .SI (n_120), .SE (tx_bit_cnt[0]), .Q (tx_bit_cnt[0]), .QN
       (UNCONNECTED1));
  SDFFTRX1 \rx_shift_reg_reg[4] (.CK (clk), .D (rx_shift_reg[4]), .RN
       (rst_n), .SI (n_151), .SE (n_116), .Q (rx_shift_reg[4]), .QN
       (UNCONNECTED2));
  SDFFTRX1 \rx_shift_reg_reg[0] (.CK (clk), .D (rx_shift_reg[0]), .RN
       (rst_n), .SI (n_151), .SE (n_115), .Q (rx_shift_reg[0]), .QN
       (UNCONNECTED3));
  SDFFTRX1 \rx_bit_index_reg[2] (.CK (clk), .D (n_134), .RN (n_117),
       .SI (n_126), .SE (rx_bit_index[2]), .Q (rx_bit_index[2]), .QN
       (UNCONNECTED4));
  SDFFTRX1 \rx_shift_reg_reg[2] (.CK (clk), .D (rx_shift_reg[2]), .RN
       (rst_n), .SI (n_151), .SE (n_113), .Q (rx_shift_reg[2]), .QN
       (UNCONNECTED5));
  SDFFTRX1 \rx_shift_reg_reg[1] (.CK (clk), .D (rx_shift_reg[1]), .RN
       (rst_n), .SI (n_151), .SE (n_105), .Q (rx_shift_reg[1]), .QN
       (UNCONNECTED6));
  SDFFTRX1 \rx_shift_reg_reg[3] (.CK (clk), .D (rx_shift_reg[3]), .RN
       (rst_n), .SI (n_151), .SE (n_110), .Q (rx_shift_reg[3]), .QN
       (UNCONNECTED7));
  SDFFTRX1 \rx_shift_reg_reg[5] (.CK (clk), .D (rx_shift_reg[5]), .RN
       (rst_n), .SI (n_151), .SE (n_103), .Q (rx_shift_reg[5]), .QN
       (UNCONNECTED8));
  SDFFTRX1 \rx_shift_reg_reg[6] (.CK (clk), .D (rx_shift_reg[6]), .RN
       (rst_n), .SI (n_151), .SE (n_102), .Q (rx_shift_reg[6]), .QN
       (UNCONNECTED9));
  SDFFTRX1 \rx_shift_reg_reg[7] (.CK (clk), .D (rx_shift_reg[7]), .RN
       (rst_n), .SI (n_151), .SE (n_137), .Q (rx_shift_reg[7]), .QN
       (UNCONNECTED10));
  JKFFX1 \sample_cnt_reg[0] (.CK (clk), .J (n_109), .K (n_85), .Q
       (sample_cnt[0]), .QN (UNCONNECTED11));
  OAI21XL g6263(.A0 (n_141), .A1 (rx_bit_index[2]), .B0 (n_127), .Y
       (n_150));
  NAND2XL g6216(.A (rst_n), .B (n_122), .Y (n_149));
  OAI21XL g6237(.A0 (n_163), .A1 (tx_bit_cnt[0]), .B0 (n_121), .Y
       (n_161));
  OAI2BB1XL g6238(.A0N (rst_n), .A1N (n_146), .B0 (n_131), .Y (n_148));
  AOI222XL g6221(.A0 (n_144), .A1 (tx_shift[4]), .B0 (n_146), .B1
       (tx_data[2]), .C0 (tx_shift[3]), .C1 (n_143), .Y (n_147));
  AOI222XL g6222(.A0 (n_144), .A1 (tx_shift[5]), .B0 (n_143), .B1
       (tx_shift[4]), .C0 (tx_data[3]), .C1 (n_146), .Y (n_145));
  OAI222XL g6250(.A0 (n_133), .A1 (n_3), .B0 (n_53), .B1 (n_104), .C0
       (n_111), .C1 (n_141), .Y (n_142));
  AOI222XL g6223(.A0 (n_144), .A1 (tx_shift[6]), .B0 (n_143), .B1
       (tx_shift[5]), .C0 (tx_data[4]), .C1 (n_146), .Y (n_140));
  AOI222XL g6224(.A0 (n_144), .A1 (tx_shift[7]), .B0 (n_143), .B1
       (tx_shift[6]), .C0 (tx_data[5]), .C1 (n_146), .Y (n_139));
  AOI222XL g6225(.A0 (n_144), .A1 (tx_shift[8]), .B0 (n_146), .B1
       (tx_data[6]), .C0 (tx_shift[7]), .C1 (n_143), .Y (n_138));
  NAND2XL g6272(.A (rst_n), .B (n_137), .Y (n_158));
  AOI222XL g6219(.A0 (n_144), .A1 (tx_shift[2]), .B0 (n_143), .B1
       (tx_shift[1]), .C0 (tx_data[0]), .C1 (n_146), .Y (n_136));
  AOI222XL g6220(.A0 (n_144), .A1 (tx_shift[3]), .B0 (n_143), .B1
       (tx_shift[2]), .C0 (tx_data[1]), .C1 (n_146), .Y (n_135));
  JKFFX1 \rx_bit_index_reg[0] (.CK (clk), .J (n_134), .K (n_133), .Q
       (rx_bit_index[0]), .QN (UNCONNECTED12));
  DFFHQX1 \sample_cnt_reg[7] (.CK (clk), .D (n_119), .Q) 
       (sample_cnt[7]));
  DFFHQX1 \sample_cnt_reg[8] (.CK (clk), .D (n_114), .Q
       (sample_cnt[8]));
  SDFFTRX1 \sample_cnt_reg[1] (.CK (clk), .D (n_83), .RN (n_72), .SI
       (n_98), .SE (sample_cnt[1]), .Q (sample_cnt[1]), .QN
       (UNCONNECTED13));
  EDFFTRX1 \rx_data_reg[1] (.CK (clk), .D (rx_shift_reg[1]), .E
       (n_132), .RN (rst_n), .Q (rx_data[1]), .QN (UNCONNECTED14));
  EDFFTRX1 \rx_data_reg[3] (.CK (clk), .D (rx_shift_reg[3]), .E
       (n_132), .RN (rst_n), .Q (rx_data[3]), .QN (UNCONNECTED15));
  EDFFTRX1 \rx_data_reg[2] (.CK (clk), .D (rx_shift_reg[2]), .E
       (n_132), .RN (rst_n), .Q (rx_data[2]), .QN (UNCONNECTED16));
  EDFFTRX1 \rx_data_reg[4] (.CK (clk), .D (rx_shift_reg[4]), .E
       (n_132), .RN (rst_n), .Q (rx_data[4]), .QN (UNCONNECTED17));
  EDFFTRX1 \rx_data_reg[5] (.CK (clk), .D (rx_shift_reg[5]), .E
       (n_132), .RN (rst_n), .Q (rx_data[5]), .QN (UNCONNECTED18));
  EDFFTRX1 \rx_data_reg[6] (.CK (clk), .D (rx_shift_reg[6]), .E
       (n_132), .RN (rst_n), .Q (rx_data[6]), .QN (UNCONNECTED19));
  EDFFTRX1 \rx_data_reg[7] (.CK (clk), .D (rx_shift_reg[7]), .E
       (n_132), .RN (rst_n), .Q (rx_data[7]), .QN (UNCONNECTED20));
  EDFFTRX1 \rx_data_reg[0] (.CK (clk), .D (rx_shift_reg[0]), .E
       (n_132), .RN (rst_n), .Q (rx_data[0]), .QN (UNCONNECTED21));
  DFFHQX1 rx_valid_reg(.CK (clk), .D (n_101), .Q (rx_valid));
  DFFHQX1 \baud_cnt_reg[5] (.CK (clk), .D (n_100), .Q (baud_cnt[5]));
  OAI21XL g6249(.A0 (n_130), .A1 (n_129), .B0 (n_128), .Y (n_131));
  INVXL g6275(.A (n_126), .Y (n_127));
  NAND3XL g6217(.A (n_124), .B (n_123), .C (tx_bit_cnt[2]), .Y (n_125));
  AOI22XL g6239(.A0 (n_143), .A1 (tx), .B0 (tx_shift[1]), .B1 (n_144),
       .Y (n_122));
  DFFHQX1 \tx_shift_reg[8] (.CK (clk), .D (n_95), .Q (tx_shift[8]));
  INVXL g6244(.A (n_120), .Y (n_121));
  DFFHQX1 \sample_cnt_reg[2] (.CK (clk), .D (n_99), .Q (sample_cnt[2]));
  NAND2XL g6274(.A (n_118), .B (n_90), .Y (n_119));
  OAI21XL g6276(.A0 (n_117), .A1 (n_141), .B0 (n_133), .Y (n_126));
  NOR3XL g6277(.A (n_106), .B (rx_bit_index[0]), .C (rx_bit_index[1]),
       .Y (n_116));
  NOR3XL g6279(.A (n_112), .B (rx_bit_index[0]), .C (rx_bit_index[1]),
       .Y (n_115));
  OAI2BB2XL g6280(.A0N (sample_cnt[8]), .A1N (n_88), .B0 (n_75), .B1
       (n_107), .Y (n_114));
  NOR2XL g6286(.A (n_112), .B (n_111), .Y (n_113));
  NOR2BXL g6287(.AN (n_117), .B (n_112), .Y (n_110));
  OAI21XL g6288(.A0 (n_84), .A1 (n_108), .B0 (n_107), .Y (n_109));
  NOR2BXL g6289(.AN (n_117), .B (n_106), .Y (n_137));
  NOR2XL g6290(.A (n_112), .B (n_104), .Y (n_105));
  NOR2XL g6293(.A (n_106), .B (n_104), .Y (n_103));
  NOR2XL g6294(.A (n_106), .B (n_111), .Y (n_102));
  OAI2BB2XL g6300(.A0N (n_94), .A1N (n_80), .B0 (n_74), .B1 (n_79), .Y
       (n_101));
  AND2X1 g6245(.A (n_143), .B (rst_n), .Y (n_120));
  DFFHQX1 \baud_cnt_reg[8] (.CK (clk), .D (n_92), .Q (baud_cnt[8]));
  DFFHQX1 \sample_cnt_reg[6] (.CK (clk), .D (n_93), .Q (sample_cnt[6]));
  OAI21XL g6262(.A0 (n_68), .A1 (n_96), .B0 (n_25), .Y (n_100));
  OAI2BB2XL g6301(.A0N (sample_cnt[2]), .A1N (n_98), .B0 (n_70), .B1
       (n_86), .Y (n_99));
  OAI32XL g6264(.A0 (n_24), .A1 (n_38), .A2 (baud_cnt[4]), .B0 (n_69),
       .B1 (n_96), .Y (n_97));
  DFFHQX1 \sample_cnt_reg[4] (.CK (clk), .D (n_77), .Q (sample_cnt[4]));
  NAND3BXL g6246(.AN (n_144), .B (n_12), .C (rst_n), .Y (n_95));
  AND4X1 g6247(.A (n_128), .B (tx_bit_cnt[0]), .C (baud_tick), .D
       (tx_bit_cnt[1]), .Y (n_123));
  NAND3BXL g6307(.AN (rx_bit_index[2]), .B (n_89), .C (n_81), .Y
       (n_112));
  MXI2XL g6265(.S0 (tx_ready), .B (tx_valid), .A (baud_tick), .Y
       (n_143));
  NAND3BXL g6278(.AN (tx_bit_cnt[1]), .B (baud_tick), .C
       (tx_bit_cnt[0]), .Y (n_130));
  AOI211XL g6291(.A0 (n_94), .A1 (rx_state[1]), .B0 (n_55), .C0 (n_26),
       .Y (n_133));
  NAND2XL g6295(.A (n_118), .B (n_73), .Y (n_93));
  OAI21XL g6297(.A0 (n_64), .A1 (n_96), .B0 (n_62), .Y (n_92));
  OAI32XL g6298(.A0 (n_61), .A1 (baud_cnt[6]), .A2 (baud_cnt[7]), .B0
       (n_65), .B1 (n_96), .Y (n_91));
  AOI22XL g6299(.A0 (n_87), .A1 (n_29), .B0 (sample_cnt[7]), .B1
       (n_58), .Y (n_90));
  DFFHQX1 \sample_cnt_reg[5] (.CK (clk), .D (n_71), .Q (sample_cnt[5]));
  NAND3BXL g6304(.AN (rx_state[0]), .B (n_89), .C (rx_bit_index[2]), .Y
       (n_106));
  OAI21XL g6306(.A0 (n_87), .A1 (n_86), .B0 (n_85), .Y (n_88));
  NOR2XL g6310(.A (n_82), .B (sample_cnt[1]), .Y (n_84));
  NOR2BXL g6311(.AN (n_82), .B (sample_cnt[0]), .Y (n_83));
  NOR2XL g6312(.A (n_78), .B (n_81), .Y (n_132));
  OAI21XL g6316(.A0 (n_79), .A1 (rx_state[1]), .B0 (n_78), .Y (n_80));
  NOR2BXL g6273(.AN (baud_tick), .B (tx_ready), .Y (n_144));
  NAND2XL g6303(.A (n_118), .B (n_56), .Y (n_77));
  OAI21XL g6305(.A0 (n_75), .A1 (n_21), .B0 (n_74), .Y (n_76));
  AOI32XL g6308(.A0 (n_57), .A1 (n_72), .A2 (n_8), .B0 (n_48), .B1
       (sample_cnt[6]), .Y (n_73));
  OAI2BB2XL g6323(.A0N (sample_cnt[5]), .A1N (n_44), .B0 (n_42), .B1
       (n_47), .Y (n_71));
  AOI22XL g6324(.A0 (n_54), .A1 (n_50), .B0 (sample_cnt[2]), .B1
       (sample_cnt[1]), .Y (n_70));
  JKFFX1 \baud_cnt_reg[1] (.CK (clk), .J (n_40), .K (n_16), .Q
       (baud_cnt[1]), .QN (UNCONNECTED22));
  OAI21XL g6285(.A0 (n_67), .A1 (n_0), .B0 (baud_cnt[4]), .Y (n_69));
  OAI21XL g6292(.A0 (n_67), .A1 (n_23), .B0 (baud_cnt[5]), .Y (n_68));
  OAI211XL g6296(.A0 (n_33), .A1 (n_51), .B0 (n_52), .C0 (n_118), .Y
       (n_66));
  OAI21XL g6313(.A0 (n_63), .A1 (n_2), .B0 (baud_cnt[7]), .Y (n_65));
  OAI21XL g6315(.A0 (n_63), .A1 (n_60), .B0 (baud_cnt[8]), .Y (n_64));
  OR4X1 g6317(.A (n_61), .B (baud_cnt[6]), .C (n_60), .D (baud_cnt[8]),
       .Y (n_62));
  AOI2BB1XL g6318(.A0N (n_59), .A1N (n_141), .B0 (n_49), .Y (n_74));
  OAI21XL g6320(.A0 (n_57), .A1 (n_96), .B0 (n_46), .Y (n_58));
  AOI22XL g6322(.A0 (n_35), .A1 (n_43), .B0 (sample_cnt[4]), .B1
       (n_34), .Y (n_56));
  OAI22XL g6325(.A0 (n_59), .A1 (n_96), .B0 (rx_state[1]), .B1 (n_4),
       .Y (n_55));
  OR2X1 g6328(.A (n_54), .B (sample_cnt[2]), .Y (n_82));
  INVXL g6329(.A (n_53), .Y (n_134));
  NAND3XL g6331(.A (rx_state[1]), .B (n_59), .C (rx), .Y (n_78));
  NOR3XL g6333(.A (n_75), .B (n_6), .C (rx_bit_index[3]), .Y (n_89));
  DFFTRX1 baud_tick_reg(.CK (clk), .D (n_41), .RN (rst_n), .Q
       (baud_tick), .QN (UNCONNECTED23));
  SDFFTRX1 \baud_cnt_reg[6] (.CK (clk), .D (n_30), .RN (rst_n), .SI
       (n_32), .SE (baud_cnt[6]), .Q (UNCONNECTED24), .QN
       (baud_cnt[6]));
  NAND4XL g6321(.A (n_45), .B (n_72), .C (n_51), .D (n_50), .Y (n_52));
  NOR2BXL g6327(.AN (n_57), .B (sample_cnt[7]), .Y (n_87));
  NAND2XL g6330(.A (n_49), .B (n_59), .Y (n_53));
  OAI221XL g6314(.A0 (n_19), .A1 (baud_cnt[3]), .B0 (n_14), .B1 (n_20),
       .C0 (baud_cnt[0]), .Y (n_67));
  OAI2BB1XL g6332(.A0N (rst_n), .A1N (n_47), .B0 (n_46), .Y (n_48));
  OR2X1 g6336(.A (n_45), .B (sample_cnt[3]), .Y (n_54));
  INVXL g6338(.A (n_59), .Y (n_75));
  OAI21XL g6342(.A0 (n_86), .A1 (n_43), .B0 (n_85), .Y (n_44));
  AOI21XL g6353(.A0 (n_37), .A1 (n_94), .B0 (n_27), .Y (n_42));
  SDFFTRX1 \baud_cnt_reg[2] (.CK (clk), .D (n_9), .RN (baud_cnt[1]),
       .SI (n_17), .SE (baud_cnt[2]), .Q (baud_cnt[2]), .QN
       (UNCONNECTED25));
  OAI31XL g6319(.A0 (n_39), .A1 (n_36), .A2 (baud_cnt[1]), .B0 (rst_n),
       .Y (n_41));
  JKFFX1 \baud_cnt_reg[3] (.CK (clk), .J (n_10), .K (n_15), .Q
       (baud_cnt[3]), .QN (n_20));
  AOI2BB1XL g6334(.A0N (n_39), .A1N (n_7), .B0 (n_38), .Y (n_40));
  NOR2XL g6337(.A (n_47), .B (sample_cnt[6]), .Y (n_57));
  NOR2XL g6339(.A (n_47), .B (n_37), .Y (n_59));
  OR2X1 g6340(.A (n_22), .B (n_36), .Y (n_63));
  OAI21XL g6341(.A0 (n_31), .A1 (n_108), .B0 (n_28), .Y (n_35));
  OAI21XL g6343(.A0 (n_51), .A1 (n_96), .B0 (n_33), .Y (n_34));
  INVXL g6348(.A (n_32), .Y (n_61));
  OAI2BB1XL g6351(.A0N (sample_cnt[0]), .A1N (n_72), .B0 (n_85), .Y
       (n_98));
  NAND2BXL g6345(.AN (sample_cnt[4]), .B (n_31), .Y (n_45));
  NOR2XL g6349(.A (n_30), .B (n_96), .Y (n_32));
  OAI2BB1XL g6350(.A0N (sample_cnt[8]), .A1N (n_94), .B0 (n_28), .Y
       (n_29));
  INVXL g6359(.A (n_107), .Y (n_27));
  NAND2BXL g6344(.AN (sample_cnt[5]), .B (n_43), .Y (n_47));
  AOI2BB1XL g6352(.A0N (n_50), .A1N (n_96), .B0 (n_26), .Y (n_33));
  OR4X1 g6354(.A (n_24), .B (n_38), .C (n_23), .D (baud_cnt[5]), .Y
       (n_25));
  MX2XL g6355(.S0 (baud_cnt[6]), .B (n_5), .A (n_24), .Y (n_22));
  NAND2XL g6358(.A (rx), .B (n_26), .Y (n_85));
  NOR2BXL g6360(.AN (n_21), .B (n_49), .Y (n_107));
  INVXL g6374(.A (n_72), .Y (n_86));
  NAND2XL g6346(.A (n_20), .B (n_18), .Y (n_39));
  NOR2BXL g6347(.AN (n_18), .B (baud_cnt[1]), .Y (n_19));
  OR2X1 g6356(.A (n_46), .B (rx), .Y (n_118));
  NOR2XL g6357(.A (n_37), .B (sample_cnt[5]), .Y (n_31));
  OR2X1 g6361(.A (n_24), .B (n_36), .Y (n_30));
  AOI21XL g6364(.A0 (n_11), .A1 (rst_n), .B0 (n_49), .Y (n_28));
  NAND2XL g6375(.A (n_141), .B (n_108), .Y (n_72));
  OAI21XL g6378(.A0 (baud_cnt[1]), .A1 (n_96), .B0 (n_16), .Y (n_17));
  DFFHQX1 \baud_cnt_reg[0] (.CK (clk), .D (n_13), .Q (baud_cnt[0]));
  AOI2BB1XL g6365(.A0N (n_14), .A1N (n_96), .B0 (n_13), .Y (n_15));
  MXI2XL g6366(.S0 (n_146), .B (tx_data[7]), .A (tx_shift[8]), .Y
       (n_12));
  NAND2XL g6369(.A (n_11), .B (n_94), .Y (n_21));
  AND2X1 g6373(.A (n_14), .B (n_9), .Y (n_10));
  INVXL g6376(.A (n_46), .Y (n_26));
  NOR3BXL g6362(.AN (n_50), .B (sample_cnt[3]), .C (sample_cnt[4]), .Y
       (n_43));
  NOR4BXL g6363(.AN (baud_cnt[8]), .B (n_60), .C (n_1), .D
       (baud_cnt[2]), .Y (n_18));
  OR2X1 g6368(.A (n_8), .B (sample_cnt[6]), .Y (n_37));
  NAND2BXL g6370(.AN (n_7), .B (baud_cnt[0]), .Y (n_36));
  NAND2XL g6371(.A (baud_cnt[3]), .B (n_14), .Y (n_24));
  NOR2XL g6372(.A (n_141), .B (rx_state[0]), .Y (n_49));
  NAND3XL g6377(.A (n_81), .B (n_6), .C (rst_n), .Y (n_46));
  INVXL g6389(.A (n_94), .Y (n_108));
  INVXL g6399(.A (n_128), .Y (n_163));
  INVXL g6402(.A (n_13), .Y (n_16));
  NOR3XL g6379(.A (sample_cnt[0]), .B (sample_cnt[1]), .C
       (sample_cnt[2]), .Y (n_50));
  OR3XL g6380(.A (baud_cnt[3]), .B (baud_cnt[1]), .C (baud_cnt[2]), .Y
       (n_5));
  INVXL g6381(.A (n_4), .Y (n_151));
  NAND2XL g6387(.A (rx_bit_index[0]), .B (n_3), .Y (n_104));
  NOR2XL g6390(.A (n_81), .B (n_96), .Y (n_94));
  OR2X1 g6391(.A (n_3), .B (rx_bit_index[0]), .Y (n_111));
  INVXL g6395(.A (n_38), .Y (n_9));
  NOR2XL g6398(.A (n_1), .B (baud_cnt[8]), .Y (n_2));
  NOR2XL g6400(.A (tx_ready), .B (n_96), .Y (n_128));
  NOR2XL g6403(.A (baud_cnt[0]), .B (n_96), .Y (n_13));
  OR2X1 g6401(.A (n_124), .B (tx_bit_cnt[2]), .Y (n_129));
  AND2X1 g6386(.A (baud_cnt[1]), .B (baud_cnt[2]), .Y (n_14));
  NOR2XL g6397(.A (rx_state[1]), .B (rx), .Y (n_11));
  AND2X1 g6392(.A (rx_bit_index[0]), .B (rx_bit_index[1]), .Y (n_117));
  NAND2BXL g6394(.AN (rx_ready), .B (rx_valid), .Y (n_79));
  AND2X1 g6393(.A (tx_ready), .B (tx_valid), .Y (n_146));
  NOR2XL g6383(.A (baud_cnt[3]), .B (baud_cnt[5]), .Y (n_0));
  NAND2XL g6384(.A (baud_cnt[5]), .B (baud_cnt[4]), .Y (n_7));
  OR2X1 g6385(.A (sample_cnt[8]), .B (sample_cnt[7]), .Y (n_8));
  NAND2XL g6388(.A (rst_n), .B (rx_state[1]), .Y (n_141));
  NAND2XL g6382(.A (rx), .B (rst_n), .Y (n_4));
  NAND2XL g6396(.A (rst_n), .B (baud_cnt[0]), .Y (n_38));
  INVXL g6408(.A (baud_cnt[6]), .Y (n_1));
  INVXL g6406(.A (rst_n), .Y (n_96));
  DFFX1 \tx_bit_cnt_reg[3] (.CK (clk), .D (n_166), .Q (UNCONNECTED26),
       .QN (n_124));
  DFFX1 \rx_bit_index_reg[1] (.CK (clk), .D (n_142), .Q
       (rx_bit_index[1]), .QN (n_3));
  DFFX1 \rx_state_reg[1] (.CK (clk), .D (n_76), .Q (rx_state[1]), .QN
       (n_6));
  DFFX1 \baud_cnt_reg[4] (.CK (clk), .D (n_97), .Q (baud_cnt[4]), .QN
       (n_23));
  DFFX1 \baud_cnt_reg[7] (.CK (clk), .D (n_91), .Q (baud_cnt[7]), .QN
       (n_60));
  DFFX1 \sample_cnt_reg[3] (.CK (clk), .D (n_66), .Q (sample_cnt[3]),
       .QN (n_51));
  DFFX1 \rx_state_reg[0] (.CK (clk), .D (n_159), .Q (rx_state[0]), .QN
       (n_81));
endmodule

